# Generated by Django 5.2.4 on 2026-01-26 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='products',
            field=models.ManyToManyField(related_name='offers_tmp', to='offer_app.product'),
        ),
    ]
