# Generated by Django 4.2.7 on 2025-11-19 06:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('offer_app', '0002_remove_category_brand_remove_category_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offer',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='offer',
            name='product',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='shares_count',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='views_count',
        ),
        migrations.AddField(
            model_name='offer',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='offer_app.category'),
        ),
        migrations.AddField(
            model_name='offer',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='offer_link',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='offer',
            name='products',
            field=models.ManyToManyField(related_name='offers', to='offer_app.product'),
        ),
        migrations.AddField(
            model_name='offer',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='offer_qr/'),
        ),
        migrations.AddField(
            model_name='offer',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='offer',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='offer',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
