# Generated by Django 5.2.4 on 2026-01-26 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer_app', '0002_alter_offer_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='products',
            field=models.ManyToManyField(related_name='offers', to='offer_app.product'),
        ),
    ]
