# Generated by Django 5.2.4 on 2026-01-29 08:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer_app', '0003_alter_offer_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferMaster',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('scheduled', 'Scheduled')], default='active', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='offer_master_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_masters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Offer Master',
                'verbose_name_plural': 'Offer Masters',
                'ordering': ['-created_at'],
            },
        ),
    ]
