# Generated by Django 5.2.4 on 2026-01-29 09:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer_app', '0004_offermaster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offermaster',
            name='image',
        ),
        migrations.CreateModel(
            name='OfferMasterMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='offer_master_media/')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('pdf', 'PDF')], max_length=10)),
                ('order', models.IntegerField(default=0)),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('offer_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='offer_app.offermaster')),
            ],
            options={
                'verbose_name': 'Offer Master Media',
                'verbose_name_plural': 'Offer Master Media Files',
                'ordering': ['order', 'uploaded_at'],
            },
        ),
    ]
