# Generated by Django 5.2.4 on 2026-02-13 13:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer_app', '0005_remove_offermaster_image_offermastermedia'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchMaster',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('branch_name', models.CharField(max_length=255)),
                ('branch_code', models.CharField(max_length=50, unique=True)),
                ('location', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('pincode', models.CharField(blank=True, max_length=20, null=True)),
                ('country', models.CharField(default='India', max_length=100)),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('manager_name', models.CharField(blank=True, max_length=255, null=True)),
                ('manager_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('branch_image', models.ImageField(blank=True, null=True, upload_to='branch_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Branch Master',
                'verbose_name_plural': 'Branch Masters',
                'ordering': ['-created_at'],
            },
        ),
    ]
