# Generated by Django 5.2.4 on 2026-02-14 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer_app', '0006_branchmaster'),
    ]

    operations = [
        migrations.AddField(
            model_name='offermaster',
            name='branches',
            field=models.ManyToManyField(blank=True, help_text='Branches where this offer is available', related_name='offers', to='offer_app.branchmaster'),
        ),
    ]
