# Generated by Django 5.2.4 on 2026-02-20 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer_app', '0007_offermaster_branches'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchmaster',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='branch_qr/'),
        ),
    ]
