# Generated by Django 5.2.4 on 2026-02-23 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer_app', '0008_branchmaster_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
