# Generated by Django 5.2.4 on 2026-02-26 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer_app', '0010_user_client_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='offermaster',
            name='offer_end_time',
            field=models.TimeField(blank=True, help_text='Daily end time for hourly offers (e.g. 17:00)', null=True),
        ),
        migrations.AddField(
            model_name='offermaster',
            name='offer_start_time',
            field=models.TimeField(blank=True, help_text='Daily start time for hourly offers (e.g. 15:00)', null=True),
        ),
    ]
